import React, { useMemo } from 'react';
import type { PropsWithChildren } from 'react';
import { Image } from 'react-native';

type CountryProps = PropsWithChildren<{
  isoCode: string;
  size: number;
  style?: any;
}>;

const CountryFlag = ({
  isoCode,
  size,
  style,
}: CountryProps): React.JSX.Element => {
  const imageMap: any = useMemo(() => {
    return {
      af: require('assets/images/w80/af.png'),
      al: require('assets/images/w80/al.png'),
      dz: require('assets/images/w80/dz.png'),
      as: require('assets/images/w80/as.png'),
      ad: require('assets/images/w80/ad.png'),
      ao: require('assets/images/w80/ao.png'),
      ai: require('assets/images/w80/ai.png'),
      aq: require('assets/images/w80/aq.png'),
      ag: require('assets/images/w80/ag.png'),
      ar: require('assets/images/w80/ar.png'),
      am: require('assets/images/w80/am.png'),
      aw: require('assets/images/w80/aw.png'),
      au: require('assets/images/w80/au.png'),
      at: require('assets/images/w80/at.png'),
      az: require('assets/images/w80/az.png'),
      bs: require('assets/images/w80/bs.png'),
      bh: require('assets/images/w80/bh.png'),
      bd: require('assets/images/w80/bd.png'),
      bb: require('assets/images/w80/bb.png'),
      by: require('assets/images/w80/by.png'),
      be: require('assets/images/w80/be.png'),
      bz: require('assets/images/w80/bz.png'),
      bj: require('assets/images/w80/bj.png'),
      bm: require('assets/images/w80/bm.png'),
      bt: require('assets/images/w80/bt.png'),
      bo: require('assets/images/w80/bo.png'),
      ba: require('assets/images/w80/ba.png'),
      bw: require('assets/images/w80/bw.png'),
      br: require('assets/images/w80/br.png'),
      bn: require('assets/images/w80/bn.png'),
      bg: require('assets/images/w80/bg.png'),
      bf: require('assets/images/w80/bf.png'),
      bi: require('assets/images/w80/bi.png'),
      kh: require('assets/images/w80/kh.png'),
      cm: require('assets/images/w80/cm.png'),
      ca: require('assets/images/w80/ca.png'),
      cv: require('assets/images/w80/cv.png'),
      ky: require('assets/images/w80/ky.png'),
      cf: require('assets/images/w80/cf.png'),
      td: require('assets/images/w80/td.png'),
      cl: require('assets/images/w80/cl.png'),
      cn: require('assets/images/w80/cn.png'),
      co: require('assets/images/w80/co.png'),
      km: require('assets/images/w80/km.png'),
      cg: require('assets/images/w80/cg.png'),
      cr: require('assets/images/w80/cr.png'),
      hr: require('assets/images/w80/hr.png'),
      cu: require('assets/images/w80/cu.png'),
      cy: require('assets/images/w80/cy.png'),
      cz: require('assets/images/w80/cz.png'),
      dk: require('assets/images/w80/dk.png'),
      dj: require('assets/images/w80/dj.png'),
      dm: require('assets/images/w80/dm.png'),
      do: require('assets/images/w80/do.png'),
      ec: require('assets/images/w80/ec.png'),
      eg: require('assets/images/w80/eg.png'),
      sv: require('assets/images/w80/sv.png'),
      gq: require('assets/images/w80/gq.png'),
      er: require('assets/images/w80/er.png'),
      ee: require('assets/images/w80/ee.png'),
      et: require('assets/images/w80/et.png'),
      fj: require('assets/images/w80/fj.png'),
      fi: require('assets/images/w80/fi.png'),
      fr: require('assets/images/w80/fr.png'),
      ga: require('assets/images/w80/ga.png'),
      gm: require('assets/images/w80/gm.png'),
      ge: require('assets/images/w80/ge.png'),
      de: require('assets/images/w80/de.png'),
      gh: require('assets/images/w80/gh.png'),
      gr: require('assets/images/w80/gr.png'),
      gd: require('assets/images/w80/gd.png'),
      gu: require('assets/images/w80/gu.png'),
      gt: require('assets/images/w80/gt.png'),
      gn: require('assets/images/w80/gn.png'),
      gw: require('assets/images/w80/gw.png'),
      gy: require('assets/images/w80/gy.png'),
      ht: require('assets/images/w80/ht.png'),
      hn: require('assets/images/w80/hn.png'),
      hk: require('assets/images/w80/hk.png'),
      hu: require('assets/images/w80/hu.png'),
      is: require('assets/images/w80/is.png'),
      in: require('assets/images/w80/in.png'),
      id: require('assets/images/w80/id.png'),
      ir: require('assets/images/w80/ir.png'),
      iq: require('assets/images/w80/iq.png'),
      ie: require('assets/images/w80/ie.png'),
      il: require('assets/images/w80/il.png'),
      it: require('assets/images/w80/it.png'),
      jm: require('assets/images/w80/jm.png'),
      jp: require('assets/images/w80/jp.png'),
      jo: require('assets/images/w80/jo.png'),
      kz: require('assets/images/w80/kz.png'),
      ke: require('assets/images/w80/ke.png'),
      ki: require('assets/images/w80/ki.png'),
      kp: require('assets/images/w80/kp.png'),
      kr: require('assets/images/w80/kr.png'),
      kw: require('assets/images/w80/kw.png'),
      kg: require('assets/images/w80/kg.png'),
      la: require('assets/images/w80/la.png'),
      lv: require('assets/images/w80/lv.png'),
      lb: require('assets/images/w80/lb.png'),
      ls: require('assets/images/w80/ls.png'),
      lr: require('assets/images/w80/lr.png'),
      ly: require('assets/images/w80/ly.png'),
      li: require('assets/images/w80/li.png'),
      lt: require('assets/images/w80/lt.png'),
      lu: require('assets/images/w80/lu.png'),
      mo: require('assets/images/w80/mo.png'),
      mk: require('assets/images/w80/mk.png'),
      mg: require('assets/images/w80/mg.png'),
      mw: require('assets/images/w80/mw.png'),
      my: require('assets/images/w80/my.png'),
      mv: require('assets/images/w80/mv.png'),
      ml: require('assets/images/w80/ml.png'),
      mt: require('assets/images/w80/mt.png'),
      mh: require('assets/images/w80/mh.png'),
      mr: require('assets/images/w80/mr.png'),
      mu: require('assets/images/w80/mu.png'),
      mx: require('assets/images/w80/mx.png'),
      fm: require('assets/images/w80/fm.png'),
      md: require('assets/images/w80/md.png'),
      mc: require('assets/images/w80/mc.png'),
      mn: require('assets/images/w80/mn.png'),
      me: require('assets/images/w80/me.png'),
      ma: require('assets/images/w80/ma.png'),
      mz: require('assets/images/w80/mz.png'),
      mm: require('assets/images/w80/mm.png'),
      na: require('assets/images/w80/na.png'),
      nr: require('assets/images/w80/nr.png'),
      np: require('assets/images/w80/np.png'),
      nl: require('assets/images/w80/nl.png'),
      nz: require('assets/images/w80/nz.png'),
      ni: require('assets/images/w80/ni.png'),
      ne: require('assets/images/w80/ne.png'),
      ng: require('assets/images/w80/ng.png'),
      no: require('assets/images/w80/no.png'),
      om: require('assets/images/w80/om.png'),
      pk: require('assets/images/w80/pk.png'),
      pw: require('assets/images/w80/pw.png'),
      pa: require('assets/images/w80/pa.png'),
      pg: require('assets/images/w80/pg.png'),
      py: require('assets/images/w80/py.png'),
      pe: require('assets/images/w80/pe.png'),
      ph: require('assets/images/w80/ph.png'),
      pl: require('assets/images/w80/pl.png'),
      pt: require('assets/images/w80/pt.png'),
      pr: require('assets/images/w80/pr.png'),
      qa: require('assets/images/w80/qa.png'),
      ro: require('assets/images/w80/ro.png'),
      ru: require('assets/images/w80/ru.png'),
      rw: require('assets/images/w80/rw.png'),
      ws: require('assets/images/w80/ws.png'),
      sm: require('assets/images/w80/sm.png'),
      st: require('assets/images/w80/st.png'),
      sa: require('assets/images/w80/sa.png'),
      sn: require('assets/images/w80/sn.png'),
      rs: require('assets/images/w80/rs.png'),
      sc: require('assets/images/w80/sc.png'),
      sl: require('assets/images/w80/sl.png'),
      sg: require('assets/images/w80/sg.png'),
      sx: require('assets/images/w80/sx.png'),
      sk: require('assets/images/w80/sk.png'),
      si: require('assets/images/w80/si.png'),
      sb: require('assets/images/w80/sb.png'),
      so: require('assets/images/w80/so.png'),
      za: require('assets/images/w80/za.png'),
      ss: require('assets/images/w80/ss.png'),
      es: require('assets/images/w80/es.png'),
      lk: require('assets/images/w80/lk.png'),
      sd: require('assets/images/w80/sd.png'),
      sr: require('assets/images/w80/sr.png'),
      sz: require('assets/images/w80/sz.png'),
      se: require('assets/images/w80/se.png'),
      ch: require('assets/images/w80/ch.png'),
      sy: require('assets/images/w80/sy.png'),
      tj: require('assets/images/w80/tj.png'),
      tz: require('assets/images/w80/tz.png'),
      th: require('assets/images/w80/th.png'),
      tl: require('assets/images/w80/tl.png'),
      tg: require('assets/images/w80/tg.png'),
      to: require('assets/images/w80/to.png'),
      tn: require('assets/images/w80/tn.png'),
      tr: require('assets/images/w80/tr.png'),
      tm: require('assets/images/w80/tm.png'),
      tv: require('assets/images/w80/tv.png'),
      ug: require('assets/images/w80/ug.png'),
      ua: require('assets/images/w80/ua.png'),
      ae: require('assets/images/w80/ae.png'),
      gb: require('assets/images/w80/gb.png'),
      us: require('assets/images/w80/us.png'),
      uy: require('assets/images/w80/uy.png'),
      uz: require('assets/images/w80/uz.png'),
      vu: require('assets/images/w80/vu.png'),
      ve: require('assets/images/w80/ve.png'),
      vn: require('assets/images/w80/vn.png'),
      wf: require('assets/images/w80/wf.png'),
      eh: require('assets/images/w80/eh.png'),
      ye: require('assets/images/w80/ye.png'),
      zm: require('assets/images/w80/zm.png'),
      zw: require('assets/images/w80/zw.png'),
      null: require('assets/images/w80/null.png'),
    };
  }, []);
  const IMAGE_PATH = imageMap[isoCode];
  return (
    <Image
      source={IMAGE_PATH}
      style={{ width: size * 1.6, height: size, ...style }}
    />
  );
};

export default CountryFlag;
